'use client';
import {useEffect,useRef,useState} from 'react';
import type * as Leaflet from 'leaflet';
import {Crosshair,LoaderCircle,MapPin} from 'lucide-react';
import {type Place,type Area} from '@/lib/resources';
import {type Language,translations} from '@/lib/i18n';
const colors={shelter:'#06786e',drc:'#1f5fae',responder:'#b76725',hospital:'#c2495f',vet:'#7c59b4',manager:'#336497'};
const symbols={shelter:'⌂',drc:'R',responder:'✦',hospital:'+',vet:'P',manager:'i'};
export default function ResourceMap({area,places,zones,language,onSelect,focusId}:{area:Area;places:Place[];zones:boolean;language:Language;onSelect:(p:Place)=>void;focusId?:string}){
 const el=useRef<HTMLDivElement>(null),map=useRef<Leaflet.Map|null>(null),library=useRef<typeof Leaflet|null>(null),markers=useRef<Leaflet.LayerGroup|null>(null),zoneLayer=useRef<Leaflet.GeoJSON|null>(null),callback=useRef(onSelect);const [ready,setReady]=useState(false),[error,setError]=useState(false),[zoneStatus,setZoneStatus]=useState('');const t=translations[language];callback.current=onSelect;
 useEffect(()=>{let disposed=false;import('leaflet').then(L=>{if(disposed||!el.current)return;library.current=L;const m=L.map(el.current,{center:[area.lat,area.lng],zoom:12,zoomControl:false,scrollWheelZoom:false,attributionControl:true});map.current=m;L.control.zoom({position:'bottomright'}).addTo(m);let tileErrors=0;L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>'}).on('tileerror',()=>{tileErrors++;if(tileErrors>8)setError(true);}).addTo(m);markers.current=L.layerGroup().addTo(m);const resize=new ResizeObserver(()=>m.invalidateSize());resize.observe(el.current);(m as any).__resize=resize;setReady(true);}).catch(()=>setError(true));return()=>{disposed=true;(map.current as any)?.__resize?.disconnect();map.current?.remove();map.current=null;};},[]);
 useEffect(()=>{const L=library.current,m=map.current;if(!ready||!L||!m||!markers.current)return;markers.current.clearLayers();const areaLabel=document.createElement('span');areaLabel.textContent=area.label;L.circleMarker([area.lat,area.lng],{radius:7,color:'#fff',weight:3,fillColor:'#246bfd',fillOpacity:1}).bindTooltip(areaLabel).addTo(markers.current);for(const p of places){const icon=L.divIcon({className:'resource-pin-wrap',html:`<span class="resource-pin ${p.kind}" style="--pin:${colors[p.kind]}">${symbols[p.kind]}</span>`,iconSize:[38,44],iconAnchor:[19,42]});const marker=L.marker([p.lat,p.lng],{icon,title:p.name,keyboard:true});const tooltip=document.createElement('span');tooltip.textContent=p.name;marker.bindTooltip(tooltip,{direction:'top',offset:[0,-38]}).on('click',()=>callback.current(p)).addTo(markers.current);marker.getElement()?.setAttribute('aria-label',p.name);}m.setView([area.lat,area.lng],12,{animate:false});},[ready,area,places,language]);
 useEffect(()=>{if(!focusId)return;const p=places.find(p=>p.id===focusId);if(p)map.current?.setView([p.lat,p.lng],14,{animate:false});},[focusId,places]);
 useEffect(()=>{const L=library.current,m=map.current;if(!ready||!L||!m)return;let active=true;const controller=new AbortController();if(zoneLayer.current){m.removeLayer(zoneLayer.current);zoneLayer.current=null;}setZoneStatus('');if(!zones)return;
 const local=area.state==='VA'&&area.locality?.toLowerCase().includes('norfolk');const url=local?'/norfolk-zones.geojson':`/api/zones?lat=${area.lat}&lng=${area.lng}`;
 fetch(url,{signal:controller.signal}).then(r=>{if(!r.ok)throw new Error();return r.json();}).then((d:any)=>{if(!active)return;if(!d.features?.length){setZoneStatus(t.zoneMissing);return;}zoneLayer.current=L.geoJSON(d,{style:(feature)=>{const zone=String(feature?.properties.Zone||'A')[0];const palette:Record<string,string>={A:'#d97852',B:'#efbd58',C:'#77b493',D:'#939acd'};return {color:palette[zone]||'#748392',weight:1.3,fillColor:palette[zone]||'#748392',fillOpacity:.20};},onEachFeature:(f,layer)=>{const text=document.createElement('div');text.textContent=`${t.zones}: ${f.properties.Zone} · ${f.properties.Locality}. ${t.zonesNote}`;layer.bindPopup(text);}}).addTo(m);zoneLayer.current.bringToBack();}).catch(e=>{if(active&&e.name!=='AbortError')setZoneStatus(t.zoneMissing);});return()=>{active=false;controller.abort();};},[zones,area,ready,language]);
 return <div className="map-container"><div ref={el} className="leaflet-surface" role="region" aria-label={`${t.map}: ${area.label}`}/>{!ready&&<div className="map-loading"><LoaderCircle className="spin"/>{t.mapLoading}</div>}{error&&<div className="map-notice"><MapPin size={17}/>{t.mapError}</div>}{zoneStatus&&<div className="map-notice">{zoneStatus}</div>}<button className="map-center icon-button" onClick={()=>map.current?.setView([area.lat,area.lng],12,{animate:false})} aria-label={t.center}><Crosshair size={19}/></button><div className="map-location"><span className="location-dot"/>{area.label}</div>{zones&&<div className="zone-legend">{['A','B','C','D'].map((z,i)=><span key={z}><i style={{background:['#d97852','#efbd58','#77b493','#939acd'][i]}}/>{t.zones.split(' ')[0]} {z}</span>)}</div>}</div>;
}
