import {json,fetchJson,validPoint,geocode} from '@/lib/server';
import {nearest,seedFor,miles,type Place,type Area} from '@/lib/resources';
import managers from '@/lib/va-managers.json';
async function osm(area:Area):Promise<Place[]>{const {lat,lng}=area;const query=`[out:json][timeout:12];(nwr(around:35000,${lat},${lng})[amenity~"^(fire_station|police|hospital|veterinary)$"];nwr(around:35000,${lat},${lng})[emergency=ambulance_station];);out center tags 250;`;const data=await fetchJson('https://overpass-api.de/api/interpreter',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({data:query})},16000);return (data.elements||[]).filter((e:any)=>e.tags?.name).map((e:any)=>{const t=e.tags;const kind=t.amenity==='hospital'?'hospital':t.amenity==='veterinary'?'vet':'responder';return {id:`osm-${e.type}-${e.id}`,kind,name:t.name,address:[t['addr:housenumber'],t['addr:street'],t['addr:city'],t['addr:postcode']].filter(Boolean).join(' '),lat:e.lat??e.center?.lat,lng:e.lon??e.center?.lon,phone:t.phone||t['contact:phone']||undefined,url:`https://www.openstreetmap.org/${e.type}/${e.id}`,source:'community'};});}
async function shelters(area:Area):Promise<Place[]>{const params=new URLSearchParams({f:'json',where:'1=1',geometry:`${area.lng},${area.lat}`,geometryType:'esriGeometryPoint',inSR:'4326',distance:'80',units:'esriSRUnit_Kilometer',outFields:'shelter_id,shelter_name,address_1,city,state,zip,org_main_phone,shelter_status_code,reporting_period',outSR:'4326',returnGeometry:'true'});const base='https://gis.fema.gov/arcgis/rest/services/NSS/FEMA_NSS/FeatureServer/0';const d=await fetchJson(base+'/query?'+params,{},10000);if(d.error||!Array.isArray(d.features))throw new Error();return d.features.map((x:any)=>{const a=x.attributes;return {id:`fema-${a.shelter_id}`,kind:'shelter',name:a.shelter_name,address:[a.address_1,a.city,a.state,a.zip].filter(Boolean).join(', '),lat:x.geometry?.y,lng:x.geometry?.x,phone:a.org_main_phone||undefined,url:base,source:'official',reportedOpen:a.shelter_status_code==='OPEN',note:a.reporting_period?`FEMA reporting period: ${a.reporting_period}`:undefined};});}
async function manager(area:Area):Promise<Place[]>{if(area.state!=='VA')return [];const local=(area.locality||area.label.split(',')[0]).replace(/\s+(city|county)$/i,'').trim().toLowerCase();const m=managers.find(x=>x.locality.replace(/\s+(city|county)$/i,'').trim().toLowerCase()===local);if(!m||!m.address)return [];const g=await geocode(m.address);if(!g[0])return [];return [{id:'manager-'+m.locality,kind:'manager',name:m.name?`${m.name} · ${m.title}`:`${m.locality} Emergency Management`,address:m.address,lat:g[0].lat,lng:g[0].lng,phone:m.phone||undefined,email:m.email||undefined,url:'https://lemd.vdem.virginia.gov/public/',source:'official'}];}
export async function GET(request:Request){const p=new URL(request.url).searchParams,lat=Number(p.get('lat')),lng=Number(p.get('lng'));if(!p.has('lat')||!p.has('lng')||!validPoint(lat,lng))return json({error:'Invalid location'},400);const area:Area={lat,lng,label:(p.get('label')||'').slice(0,120),state:(p.get('state')||'').slice(0,2),locality:(p.get('locality')||'').slice(0,80)};const base=seedFor(area);
 const results=await Promise.allSettled([osm(area),shelters(area),base.some(p=>p.kind==='manager')?Promise.resolve([]):manager(area),fetchJson(`https://api.weather.gov/alerts/active?point=${lat.toFixed(4)},${lng.toFixed(4)}`,{headers:{'Accept':'application/geo+json','User-Agent':'HarborDisasterNavigator/1.0'}},11000)]);
 let places:Place[]=[...base];for(let i=0;i<3;i++){const r=results[i];if(r.status==='fulfilled'){for(const place of r.value as Place[]){if(!places.some(p=>p.kind===place.kind&&(miles(p,place)<0.12||p.name.toLowerCase()===place.name.toLowerCase())))places.push(place);}}}
 const alerts=results[3].status==='fulfilled'&&Array.isArray(results[3].value.features)?results[3].value.features.map((f:any)=>({id:f.id,...f.properties})):null;
 return json({places:nearest(places,area),alerts,checkedAt:new Date().toISOString(),partial:results.some(r=>r.status==='rejected'),scope:'nearest among available directory listings',radiusMiles:50});
}
